version: "2"

services:
  app:
    image: rciphertext/stocks_spe:latest
    ports:
      - "8000:8000"
    
    command: >

      sh -c "python manage.py migrate && python manage.py makemigrations stock && python manage.py migrate && ./manage.py test stock &&python manage.py runserver 0.0.0.0:8000"